--liquibase formatted sql
--changeset RGRZEGORCZYK:expenses_h
--comment Expenses_h audit table
--rollback DROP TABLE EXPENSES_H;
create table EXPENSES_h
(
  hist_id number GENERATED BY DEFAULT ON NULL AS IDENTITY INCREMENT BY 1 START WITH 1 CACHE 20 NOT NULL,
  hist_op_type char(1 char) not null,
  hist_user varchar2(50 CHAR) not null,
  hist_op_ts timestamp(6) not null, 
  ID NUMBER not null, 
  EXPENSE_TYPES_ID NUMBER, 
  EXPENSE_DATE DATE, 
  VALUE NUMBER, 
  QUANTITY NUMBER (8,2),
  UNIT_PRICE NUMBER (16,2),
  IS_RETURNED CHAR(1) DEFAULT 'N',
  RETURN_WIRE_RECEIVED CHAR(1) DEFAULT 'N',
  RETURN_VALUE NUMBER (16,2),
  COMMENTS VARCHAR2(4000 char), 
  CREATED DATE, 
  CREATED_BY VARCHAR2(255 char), 
  UPDATED DATE, 
  UPDATED_BY VARCHAR2(255 char),
  CONSTRAINT EXPENSES_h_PK PRIMARY KEY (hist_id) ENABLE 
);