--liquibase formatted sql
--changeset RGRZEGORCZYK:expense_groups
--comment expense_groups table
--rollback DROP TABLE expense_groups;
create table expense_groups (
    id                             number generated by default on null as identity start with 500
                                   constraint expense_groups_id_pk primary key,
    name                           varchar2(255),
    comments                       varchar2(4000),
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null
);
