--liquibase formatted sql
--changeset RGRZEGORCZYK:expense_types
--comment expense_types table
--rollback DROP TABLE expense_types;
create table expense_types (
    id                             number generated by default on null as identity  start with 500
                                   constraint expense_types_id_pk primary key,
    name                           varchar2(255),
    comments                       varchar2(4000),
    created                        date not null,
    created_by                     varchar2(255) not null,
    updated                        date not null,
    updated_by                     varchar2(255) not null,
    expense_group_id               number,
    display_order                  number
);
