--liquibase formatted sql
--changeset RGRZEGORCZYK:PERIODS_CONF
--comment PERIODS_CONF table
--rollback DROP TABLE PERIODS_CONF;
CREATE TABLE PERIODS_CONF 
(	CODE VARCHAR2(100 CHAR), 
  NAME VARCHAR2(200 CHAR), 
  TYPE VARCHAR2(20 CHAR), 
  DATE_FROM DATE, 
  DATE_TO DATE
);

COMMENT ON COLUMN PERIODS_CONF.CODE IS 'Period code. Primary key';

COMMENT ON COLUMN PERIODS_CONF.NAME IS 'Period code name';

COMMENT ON COLUMN PERIODS_CONF.TYPE IS 'Type of period';

COMMENT ON COLUMN PERIODS_CONF.DATE_FROM IS 'Date from';

COMMENT ON COLUMN PERIODS_CONF.DATE_TO IS 'Date to';

COMMENT ON TABLE  PERIODS_CONF  IS 'Table with period codes';

CREATE UNIQUE INDEX PERIODS_PK ON PERIODS_CONF (CODE);

ALTER TABLE PERIODS_CONF MODIFY (CODE NOT NULL ENABLE);

ALTER TABLE PERIODS_CONF MODIFY (NAME NOT NULL ENABLE);

ALTER TABLE PERIODS_CONF MODIFY (TYPE NOT NULL ENABLE);

ALTER TABLE PERIODS_CONF MODIFY (DATE_FROM NOT NULL ENABLE);

ALTER TABLE PERIODS_CONF MODIFY (DATE_TO NOT NULL ENABLE);

ALTER TABLE PERIODS_CONF ADD CONSTRAINT PERIODS_PK PRIMARY KEY (CODE);

ALTER TABLE PERIODS_CONF ADD CONSTRAINT PERIODS_CONF_CHK1 CHECK (TYPE IN ('DAY', 'WEEK', 'MONTH', 'QUARTER', 'SEMI-YEAR', 'YEAR')) ENABLE;