--liquibase formatted sql
--changeset rgrzegorczyk:EXPENSE_TYPES_FK1
--rollback  ALTER TABLE EXPENSE_TYPES DROP CONSTRAINT EXPENSE_TYPES_FK1;
ALTER TABLE EXPENSE_TYPES ADD CONSTRAINT EXPENSE_TYPES_FK1 FOREIGN KEY (EXPENSE_GROUP_ID)
	  REFERENCES EXPENSE_GROUPS (ID) ON DELETE CASCADE ENABLE;